### ISSUE TITLE
Win Crash

### ISSUE THREAD

**Issue by Centoller** [larryTheCoder/SkyWarsForPE#92] opened 2020-01-06 09:08 UTC
when winning a game in Skywars the server closes, just like creating a skywars arena (I had to create it manually from the archives) Any solution?

**Comment by larryTheCoder** [comment] 2020-01-06 13:20
Well there is no solution so far, if you still want to know about this plugin development status, head to #93

**Comment by larryTheCoder** [comment] 2020-01-06 16:11
The latest version might fix your problems, can you check?

**Comment by supercrafti** [comment] 2020-01-10 15:51
The mistake is still

**Comment by larryTheCoder** [comment] 2020-07-28 14:30
Well, fyi, this might be a duplicate of #114, also I tested the plugin today and the issue seems to be solved. Closing this issue to clear old heap issues.

**Closed by larryTheCoder** 2020-07-28 14:30 UTC
