### ISSUE TITLE
wont load

### ISSUE THREAD

**Issue by SubMGRru** [larryTheCoder/SkyWarsForPE#117] opened 2020-07-28 14:13 UTC
[17:11:55] [Server thread/CRITICAL]: Error: "Class 'poggit\libasynql\libasynql' not found" (EXCEPTION) in "plugins/SkyWarsForPE-master/src/larryTheCoder/provider/AsyncLibDatabase" at line 68
[17:11:55] [Server thread/CRITICAL]: #0 plugins/SkyWarsForPE-master/src/larryTheCoder/SkyWarsPE(163): larryTheCoder\provider\AsyncLibDatabase->__construct(object larryTheCoder\SkyWarsPE, array[4])
[17:11:55] [Server thread/CRITICAL]: #1 plugins/SkyWarsForPE-master/src/larryTheCoder/SkyWarsPE(113): larryTheCoder\SkyWarsPE->initDatabase()
[17:11:55] [Server thread/CRITICAL]: #2 src/pocketmine/plugin/PluginManager(182): larryTheCoder\SkyWarsPE->onLoad()
[17:11:55] [Server thread/CRITICAL]: #3 src/pocketmine/plugin/PluginManager(346): pocketmine\plugin\PluginManager->loadPlugin(string[86] C:\Users\aramt\OneDrive\.............. ........\gameserver\plugins\SkyWarsForPE-, array[1])
[17:11:55] [Server thread/CRITICAL]: #4 plugins/DevTools.phar/src/DevTools/DevTools(69): pocketmine\plugin\PluginManager->loadPlugins(string[67] C:\Users\aramt\OneDrive\.............. ........\gameserver\plugins\, array[1])
[17:11:55] [Server thread/CRITICAL]: #5 src/pocketmine/plugin/PluginBase(116): DevTools\DevTools->onEnable()
[17:11:55] [Server thread/CRITICAL]: #6 src/pocketmine/plugin/PluginManager(552): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
[17:11:55] [Server thread/CRITICAL]: #7 src/pocketmine/Server(1787): pocketmine\plugin\PluginManager->enablePlugin(object DevTools\DevTools)
[17:11:55] [Server thread/CRITICAL]: #8 src/pocketmine/Server(1773): pocketmine\Server->enablePlugin(object DevTools\DevTools)
[17:11:55] [Server thread/CRITICAL]: #9 src/pocketmine/Server(1532): pocketmine\Server->enablePlugins(integer 0)
[17:11:55] [Server thread/CRITICAL]: #10 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[59] C:\Users\aramt\OneDrive\.............. ........\gameserver\, string[67] C:\Users\aramt\OneDrive\.............. ........\gameserver\plugins\)
[17:11:55] [Server thread/CRITICAL]: #11 src/pocketmine/PocketMine(304): pocketmine\server()
[17:11:55] [Server thread/CRITICAL]: #12 (11): require(string[114] phar://C:/Users/aramt/OneDrive/.............. ......../gameserver/PocketMine-MP.)

**Comment by larryTheCoder** [comment] 2020-07-28 14:22
Well hello there, I see that you're attempting to run this plugin unphared. For now, I suggest that you to use a phared version of this plugin in my PoggitCI, [here is the download link](https://poggit.pmmp.io/r/98136/SkyWarsForPE_dev-63.phar)

For now, I will try to patch this issue so developers wont getting this issue while using development builds. Though this is a duplicate of #116

**Closed by larryTheCoder** 2020-07-28 14:22 UTC
